# C.E.A. IRFU/SIS/LDII
#
# @(#) $Id: Makefile,v 1.2 2010/10/27 12:09:14 cmsmgr Exp $
#
# Makefile
#

TOP=../..
include $(TOP)/configure/CONFIG

#=======================================================
# Install database record or stream protocol files in <top>/db

DB += vxStats.db
DB += vxStatsReset.db

include $(TOP)/configure/RULES
