# C.E.A. IRFU/SIS/LDII
#
# @(#) $Id: Makefile,v 1.2 2010/10/27 12:09:14 cmsmgr Exp $
#
# Makefile
#

TOP=../..
include $(TOP)/configure/CONFIG

#=======================================================
# Install GUI files in <top>/gui

GUIS += vxStats.edl

include $(TOP)/configure/RULES
