#******************************************************************************
#
# "@(#) $Id: Makefile 23 2013-03-13 15:38:34Z lussi $" 
#
# who       when       what
# --------  --------   ----------------------------------------------
# ylussign  05/11/07   created
# ylussign  24/11/09   replaced ADLS by GUIS
#
#******************************************************************************

TOP=../..

include $(TOP)/configure/CONFIG

#========================================
# Install adl files in <top>/adl

GUIS += icv196.adl
GUIS += icv296.adl

include $(TOP)/configure/RULES

